charts/copia/Chart.yaml
- This is for v0.14.0 release (https://app.clickup.com/45000662/v/dc/1ax9yp-9380/1ax9yp-12060)
=> [CU-8669ejure] Update for v0.14.0 release

charts/copia/Chart.yaml, charts/copia/values.yaml
- Update for self-hosted v0.15.0 release
=> [CU-8669mx4d9] Updating helm-chart for v0.15.0 release

charts/copia/Chart.yaml
Updating the application image version to 0.17.1
=> Release 0.17.2

charts/copia/Chart.yaml
Update infra and gitea version to v0.19.0
Clickup Link: https://app.clickup.com/t/866ajw2we
=> [CU-866ajw2we]  Update infra and gitea version to v0.19.0

charts/copia/Chart.yaml
Click up link for helm chart update: https://app.clickup.com/t/86a0re32g
Click up link for v0.20.0 release: https://app.clickup.com/t/86a0r95c5
=> [CU-86a0re32g] Update helm chart for v0.20.0 self-hosted release

charts/copia/Chart.yaml
https://app.clickup.com/t/86a0w8pu6
=> [CU-86a0w8pu9] Update helm chart for v0.21.0 self-hosted release

charts/copia/Chart.yaml
https://app.clickup.com/t/86a1at5fy
=> [CU-86a1at5fy] Update helm chart for v0.22.0 self-hosted release

charts/copia/Chart.yaml
https://app.clickup.com/45000662/v/dc/1ax9yp-27507/1ax9yp-12060
=> [CU-86a1kf58c] Update Helm Chart for v0.23.0 release

charts/copia/Chart.yaml
- Will be merged after task to validate public docker https://app.clickup.com/t/86a2qdg6r is complete
=> [CU-86a2weg2b] Bump infra and gitea version to 0.27.0 for Self-Hosted release

charts/copia/Chart.yaml
=> [CU-86a3bmzqk] Bump infra and gitea version to 0.28.0

.prettierignore, charts/copia/templates/persistent-volume.yaml, charts/copia/values.schema.json, charts/copia/values.yaml, package-lock.json, package.json
Ticket: https://app.clickup.com/t/86a44v7d9
Adds `values.schema.json` file to validate value types, format and ensure proper values are provided to our helm chart.
=> Adds values.schema.json file to enforce value types and format

charts/copia/values.schema.json
Fixes issues encountered when deploying to an actual environment.
Tested on st-pretzfact
=> Fixes issues encountered when deploying to an actual environment

.github/workflows/tests.yaml, bin/setup.sh, charts/copia/.helmignore, charts/copia/templates/deployment.yaml, charts/copia/tests/deployment_test.yaml, package.json, script/test
Ticket: https://app.clickup.com/t/86a47r1vf
This PR adds:
- Chart Unit Tests (deployment_test.yaml ATM)
- Runs `helm unittests` as pre-commit hook
- Adds GHA for running tests
=> Adds Unit Tests

charts/copia/templates/deployment.yaml, charts/copia/templates/http-svc.yaml, charts/copia/tests/configmap_test.yaml, charts/copia/tests/deployment_test.yaml, charts/copia/tests/ingress_test.yaml, charts/copia/tests/pv_test.yaml, charts/copia/tests/secret_test.yaml, charts/copia/tests/service_test.yaml, charts/copia/values.schema.json, charts/copia/values.yaml
Ticket: https://app.clickup.com/t/86a47r1wb
This PR includes:
- Fixes errors encountered while writing tests (big win)
- Expands tests for deployment.yaml
- Adds tests for service.yaml
- Adds tests for configmap.yaml 
- Adds tests for secret.yaml
- Adds tests for ingress.yaml
- Adds tests for persistent-volume.yaml
=> Adds Unit Tests for default values

charts/copia/Chart.yaml
[Self-hosted Release v0.30.0 ](https://app.clickup.com/t/86a480uw6)
=> [CU-86a480vb6] Bump gitea and infra to 0.30.0

charts/copia/values.schema.json, charts/copia/values.yaml
Ticket: https://app.clickup.com/t/86a4h74dq
=> Fixes the tls issue

charts/copia/Chart.yaml
Necessary tests are complete to publish helm-chart
Clickup: https://app.clickup.com/t/86a4n3bh1
=> [CU-86a4n3bh1] Bump gitea and infra to 0.31.0

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/templates/copia-deployment.yaml, charts/copia/tests/copia_deployment_test.yaml, charts/copia/values.schema.json, charts/copia/values.yaml, package.json
Adds preflight check init container
=> Adds preflight check init container

.github/workflows/security.yaml, charts/copia/Changelog.md
Adds trivy security scanner for postgres image
=> Adds trivy security scanner for postgres image

charts/copia/Chart.yaml
- Appversion and Infra versions have diverged and it is ok. 
- Will be merged after steps prior to helm chart update in https://app.clickup.com/t/86a51eteq is complete
Merging as this is time sensitive for DeviceLink Team. Pending access validation of image in ghcr. See https://copia-automation.slack.com/archives/C03A1D6CM7D/p1727214566581909
=> [CU-86a51eth3] Bump app and infra version for S-H v0.32.0 release

charts/copia/Chart.yaml
- Image in GHCR tested: https://app.clickup.com/t/86a56tku1
https://app.clickup.com/t/86a56tku5
=> [CU-86a56tku5] Bump gitea to v0.33.0 and infra to  v0.35.0

charts/copia/Chart.yaml
- Will not be merged until pre-reqs are complete in https://app.clickup.com/t/86a58q3mh
https://app.clickup.com/t/86a58q3p9
=> [CU-86a58q3p9] Bump gitea to v0.34.0 and infra to v0.36.0 for S-H release v0.34.0

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/templates/cm-deployment.yaml, charts/copia/tests/cm_deployment_test.yaml, charts/copia/values.schema.json
- required as far as i can tell to set `DD_AGENT_HOST` for log etc. collection
=> add deployment env to conversion manager

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/templates/cm-deployment.yaml, charts/copia/tests/cm_deployment_test.yaml
- waiting for app v35 update to change version etc
=> update conversion manager container name

charts/copia/Chart.yaml
- Will be merged when pre-req for helm-chart is complete https://app.clickup.com/t/86a643djn
=> [CU86a643dnt] Bump gitea to v0.36.0 and infra to v0.40.0

charts/copia/Changelog.md, charts/copia/Chart.yaml
Update Copia helm chart to 0.38.0.
=> Update Copia to 0.38.0

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/templates/cm-deployment.yaml, charts/copia/templates/copia-deployment.yaml
Trigger rollout on configmap or secret changes
=> Fix: Trigger rollout on configmap or secret changes

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/tests/conversion_manager_configmap_test.yaml, charts/copia/values.yaml
Updates conversion manager variables so we can define DB_NAME as well.
=> Conversion Manager variables

charts/copia/Changelog.md, charts/copia/Chart.yaml, charts/copia/templates/_helpers.tpl
Fixes conversion manager labels
=> Fixes conversion manager labels

charts/copia/Changelog.md, charts/copia/Chart.yaml
helm-chart update
For self hosted release for v0.43.0
=> SelfHost Release v0.43.0

charts/copia/Changelog.md, charts/copia/Chart.yaml
=> Updated Copia version to v0.46.0
